//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_admins")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_admin: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub identifiant: String,
    pub mdp: String,
    pub prenom: String,
    pub nom: String,
    pub email: String,
    pub acces: String,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
