//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_annonces")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_annonce: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub titre: String,
    pub titre_style: String,
    pub slug: String,
    pub rubrique: String,
    pub mots: String,
    pub date_debut: DateTime,
    pub date_fin: DateTime,
    #[sea_orm(column_type = "Text")]
    pub intro: String,
    #[sea_orm(column_type = "Text")]
    pub contenu: String,
    pub lien: String,
    pub image: String,
    pub lang: String,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
