//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_amis_webtoons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_ami_webtoon: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub ami_id: i32,
    pub coins: i32,
    pub webtoon_id: i32,
    pub ean: Option<String>,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
