//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_auteurs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_auteur: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub nom: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub description_en: String,
    pub photo: String,
    pub bda_id: String,
    pub url_dupuis: String,
    pub slug: String,
    pub lang: String,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
