//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_abonnements")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_abonnement: i32,
    pub ami_id: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub date_debut: DateTime,
    pub date_fin: DateTime,
    pub valide: i8,
    pub original_transaction_id: String,
    pub transaction_id: String,
    pub transaction_type: String,
    pub abonnement_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub info_recu: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
