//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_bcross_selling")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub text: String,
    pub label: String,
    pub url: String,
    pub img: Option<String>,
    pub serie_id: Option<i32>,
    pub saison_num: Option<i8>,
    pub webtoon_id: Option<i32>,
    pub date_crea: Option<DateTime>,
    pub date_modif: Option<DateTime>,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
