//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_coms")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_com: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub objet_type_id: i32,
    pub objet_id: i32,
    pub ami_id: i32,
    pub pseudo: String,
    #[sea_orm(column_type = "Text")]
    pub commentaire: String,
    pub com_id: Option<i32>,
    pub pouces: Option<i32>,
    pub signales: Option<i32>,
    pub modere: Option<i8>,
    pub tech: Option<String>,
    pub valide: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
