//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_magazine_revision_block")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub id_magazine_revision: i32,
    pub titre: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub block_type: i32,
    pub id_serie: Option<i32>,
    pub url_pub: Option<String>,
    pub image: Option<String>,
    pub poid: i8,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
