//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_magazine_revision")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub id_magazine: i32,
    pub intro_titre: Option<String>,
    pub titre: String,
    pub intro_description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub image: String,
    pub image_carousel: String,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub date_debut: DateTime,
    pub date_fin: DateTime,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
