//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_notifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_notification: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub importance: i8,
    pub speciale: i8,
    pub reference: String,
    pub serie_id: i32,
    pub titre: String,
    #[sea_orm(column_type = "Text")]
    pub contenu: String,
    pub contenu_mini: String,
    pub email_template: String,
    pub lien: String,
    pub image: String,
    pub date_envoi: DateTime,
    pub envois_email: i32,
    pub envois_box: i32,
    pub envois_push: i32,
    pub lang: String,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
