//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_shopcodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_code: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub code: String,
    pub nb_usage: i32,
    pub produit: String,
    pub valeur: i32,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub date_debut: DateTime,
    pub date_fin: DateTime,
    pub unefois: i8,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
