//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_shoprecompenses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub titre: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub link: String,
    pub serie_id: i32,
    pub img: String,
    pub id_type: i32,
    pub coins: i32,
    pub token: String,
    pub date_debut: DateTime,
    pub date_fin: DateTime,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub valide: i8,
    pub no_limit: i8,
    pub lang: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
