//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_shopproduits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_produit: i32,
    pub date_crea: DateTime,
    pub date_modif: DateTime,
    pub reference: String,
    pub titre: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub image: Option<String>,
    pub coins: i32,
    pub mois: Option<i32>,
    pub episodes: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub prix: Decimal,
    pub bonus: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub tva: Option<Decimal>,
    pub lang: String,
    pub valide: i8,
    pub platform: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
