//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wf_shopcodesuniques")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_codeunique: i32,
    pub date_crea: i32,
    pub date_modif: i32,
    #[sea_orm(unique)]
    pub code: String,
    pub pourcent: i32,
    pub produit: String,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub valeur: Decimal,
    pub date_debut: DateTime,
    pub date_fin: DateTime,
    pub ami_id: i32,
    pub date_utilise: DateTime,
    pub valide: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
